### ISSUE TITLE
Out of stock swatchers issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/internal---sujee-designing-tweaks#10]
Bug - if user click on out of stock swatcher then after that user not able to click on in stock swatcher product.
Exp - User should be able to click on in stock swatcher.
Ref Link - https://drive.google.com/file/d/1C8x1r8DSr2yFkAv_mObmDbWeFEJCL1QY/view
Prod Link - https://jyve4en4mfxh1oza-9594798158.shopifypreview.com/products/pre-order-3-way-hina-set?variant=39604342915150

**Comment by devAlokTripathi** [comment]
@ankitcedcoss  need to contact with app support team .

**Comment by devAlokTripathi** [comment]
@ankitcedcoss it is recheck after the response of app team back in stock app .

**Comment by ankitcedcoss** [comment]
@devAlokTripathi 
Bug Not Fixed
- Swatchers working but not showing relevant image on clicking color button.
- On clicking size buttons then also image change. It should not be happen when user click on size swatcher then product image get change.
- https://drive.google.com/file/d/1uJ0mdk61ShQKZYwPYQUCAmhGkvy4RdxF/view

**Comment by ankitcedcoss** [comment]
Bug Fixed
https://drive.google.com/file/d/1JP3W7Wo3A3DSeBDxmgDzeplsE2C5Lhap/view
