### ISSUE TITLE
User not able to login from wishlist login drawer

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/internal---sujee-designing-tweaks#17]
Bug - when user click on wishlist icon without login then login drawer appears and user enters credentials and click on login then user get redirect to login page again.
Exp - User should get login if credentials are correct from wishlist icon login drawer.
Ref Link - https://drive.google.com/file/d/1bqHlfNj2QNyu5TwnbsOlVrq6EybjW49I/view

**Comment by devAlokTripathi** [comment]
Uploading seen.mp4…

@ankitcedcoss please check its working .

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - if user trying to login from wishlist login drawer wtih correct credentials then it should be get login directly. User not get redirect to login page. 

Please check - https://drive.google.com/file/d/1VLWY_gZVsECJWLkof9nGl1dzBnSkqX6c/view

**Comment by ankitcedcoss** [comment]
@devAlokTripathi 
Bug Not Fixed - User not able to direct login from wishlist login drawer.
- https://drive.google.com/file/d/11zzbhsz1_XkJ9je4857j2T5zPwUlVQlG/view

**Comment by devAlokTripathi** [comment]
not required . @ankitcedcoss

**Comment by ankitcedcoss** [comment]
Closed on Not Required
