### ISSUE TITLE
Accordian icon UI issue on responsive - Mobile and Tab

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/internal---sujee-designing-tweaks#3]
Bug - Accordian icon UI issue on hamberger section
Exp - Accordian icon not showing closed on opening other accordian.
Ref Link - https://drive.google.com/file/d/1a0mOu78po4LJOnhTPlbszF4XLYoWtE2O/view

**Comment by ankitcedcoss** [comment]
Accordian icons not working correctly and misplacing on click.
https://drive.google.com/file/d/16wrFeHrlqxvMtLsqL7mC0eSYQIvhChb9/view

**Comment by ankitcedcoss** [comment]
@devAlokTripathi 
Bug Not Fixed - Accordian button icons not working correctly.
- https://drive.google.com/file/d/1LAO9UY2w_-pG2XE7B57sA1cnVbNHE6H2/view

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/167678032-4eee5ab3-67ae-464f-be3e-563978fc18f2.png)
@ankitcedcoss  issue fixed check and update me .

**Comment by ankitcedcoss** [comment]
Bug Fixed
