### ISSUE TITLE
Product image not changing on selecting color swatchers

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/internal---sujee-designing-tweaks#4]
Bug - Product images not changing on selecting different color swatchers.
Exp - Product should change on selecting swatchers.
Ref Link - https://drive.google.com/file/d/1vlD_AiCTifGPVEVZqx6OYJgFKXuhSctP/view

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - Swatchers not showing its respective color product image.
https://drive.google.com/file/d/1GEGb2d8sl37pGswDAfuD5IojOrCSIeI1/view

**Comment by ankitcedcoss** [comment]
Image not changing by swatchers on mobile and tab
https://drive.google.com/file/d/1se3SRxqUxNICg3s8GBdJGiHai4RZoNWH/view

**Comment by devAlokTripathi** [comment]
@ankitcedcoss it is recheck after the response of app team back in stock app .

**Comment by ankitcedcoss** [comment]
@devAlokTripathi 
Bug Not Fixed
- Swatchers working but not showing relevant image on clicking color button.
- On clicking size buttons then also image change. It should not be happen when user click on size swatcher then product image get change.
- https://drive.google.com/file/d/1uJ0mdk61ShQKZYwPYQUCAmhGkvy4RdxF/view

**Comment by Gyanendraky** [comment]
Discussed with the client and it not required for now.

**Comment by ankitcedcoss** [comment]
Bug Fixed
