### ISSUE TITLE
Size chart issue on gift card page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/internal---sujee-designing-tweaks#5]
Bug - Showing size chart button on gift card page.
Exp - No need to show size chart on gift card page
Ref Link - https://nimb.ws/iZUBsO

**Comment by devAlokTripathi** [comment]
@ankitcedcoss 
![image](https://user-images.githubusercontent.com/100207984/164077717-b4deaf87-4429-4276-a181-7641244f043d.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
